apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 1.4.0
  values:
    prometheus:
      ingress:
        enabled: true
        hosts:
        - prom.127.0.0.1.nip.io
        - prom.192.168.99.100.nip.io
        - prom.192.168.99.101.nip.io
        tls:
        - hosts:
          - prom.127.0.0.1.nip.io
          - prom.192.168.99.100.nip.io
          - prom.192.168.99.101.nip.io
    alertmanager:
      ingress:
        enabled: true
        hosts:
        - alert.127.0.0.1.nip.io
        - alert.192.168.99.100.nip.io
        - alert.192.168.99.101.nip.io
        tls:
        - hosts:
          - alert.127.0.0.1.nip.io
          - alert.192.168.99.100.nip.io
          - alert.192.168.99.101.nip.io
    grafana:
      ingress:
        enabled: true
        hosts:
        - grafana.127.0.0.1.nip.io
        - grafana.192.168.99.100.nip.io
        - grafana.192.168.99.101.nip.io
        tls:
        - hosts:
          - grafana.127.0.0.1.nip.io
          - grafana.192.168.99.100.nip.io
          - grafana.192.168.99.101.nip.io
