apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  releaseName: dashboard
  chart:
    git: https://github.com/srueg/helm-charts.git
    ref: master
    path: plex
  values:
    ingress:
      hosts:
      - plex.127.0.0.1.nip.io
      tls:
      - hosts:
        - plex.127.0.0.1.nip.io
